version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27107:27107
    volumes:
      - mongo_db:/data/db
  
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      PORT: 5000
      DB_URI: mongodb+srv://nhannt-dev:Nguyennhan4720@cluster0.zc2ox5v.mongodb.net/meabhisingh?retryWrites=true&w=majority
      JWT_SECRET: nhannt4720
      JWT_EXPIRE: 3d
      COOKIE_EXPIRE: 5
      SMPT_HOST: smtp.gmail.com
      SMPT_PORT: 465
      SMPT_SERVICE: gmail
      SMPT_MAIL: nhan.nguyentrong.dev@gmail.com
      SMPT_PASSWORD: eocuwraoppwjtapt
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}